server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8001/eureka/

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
spring:
  application:
    name: zuul-gateway-server